import { fetchMeals, getMealByCateg, getMealDetails } from '../api';

beforeEach(() => {
  fetch.resetMocks();
});

test('fetchMeals returns the correct array of objects from the fetch', async () => {
  fetch.mockResponseOnce(JSON.stringify({
    meals: [
      {
        idMeal:	'52871',
        strMeal: 'Yaki Udon',
        strDrinkAlternate:	null,
        strCategory:	'Vegetarian',
        strArea:	'Japanese',
        strInstructions:	'Boil some water in a large saucepan. Add 250ml cold water and the udon noodles. (As they are so thick, adding cold water helps them to cook a little bit slower so the middle cooks through). If using frozen or fresh noodles, cook for 2 mins or until al dente; dried will take longer, about 5-6 mins. Drain and leave in the colander.\r\nHeat 1 tbsp of the oil, add the onion and cabbage and sauté for 5 mins until softened. Add the mushrooms and some spring onions, and sauté for 1 more min. Pour in the remaining sesame oil and the noodles. If using cold noodles, let them heat through before adding the ingredients for the sauce – otherwise tip in straight away and keep stir-frying until sticky and piping hot. Sprinkle with the remaining spring onions.',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg',
        strTags:	'LowCalorie',
        strYoutube:	'https://www.youtube.com/watch?v=5Iy0MCowSvA',
        strIngredient1:	'Udon Noodles',
        strIngredient2:	'Sesame Seed Oil',
        strIngredient3:	'Onion',
        strIngredient4:	'Cabbage',
        strIngredient5:	'Shiitake Mushrooms',
        strIngredient6:	'Spring Onions',
        strIngredient7:	'Mirin',
        strIngredient8:	'Soy Sauce',
        strIngredient9:	'Caster Sugar',
        strIngredient10:	'Worcestershire Sauce',
        strIngredient11:	'',
        strIngredient12:	'',
        strIngredient13:	'',
        strIngredient14:	'',
        strIngredient15:	'',
        strIngredient16:	'',
        strIngredient17:	'',
        strIngredient18:	'',
        strIngredient19:	'',
        strIngredient20:	'',
        strMeasure1:	'250g',
        strMeasure2:	'2 tbs',
        strMeasure3:	'1 sliced',
        strMeasure4:	'0.25',
        strMeasure5:	'10',
        strMeasure6:	'4',
        strMeasure7:	'4 tbsp',
        strMeasure8:	'2 tbs',
        strMeasure9:	'1 tblsp ',
        strMeasure10:	'1 tblsp ',
        strMeasure11:	'',
        strMeasure12:	'',
        strMeasure13:	'',
        strMeasure14:	'',
        strMeasure15:	'',
        strMeasure16:	'',
        strMeasure17:	'',
        strMeasure18:	'',
        strMeasure19:	'',
        strMeasure20:	'',
        strSource:	'https://www.bbcgoodfood.com/recipes/yaki-udon',
        strImageSource:	null,
        strCreativeCommonsConfirmed:	null,
        dateModified:	null,
      },
    ],
  }));
  const res = await fetchMeals('y');
  expect(res).toEqual(
    [
      {
        idMeal:	'52871',
        strMeal: 'Yaki Udon',
        strDrinkAlternate:	null,
        strCategory:	'Vegetarian',
        strArea:	'Japanese',
        strInstructions:	'Boil some water in a large saucepan. Add 250ml cold water and the udon noodles. (As they are so thick, adding cold water helps them to cook a little bit slower so the middle cooks through). If using frozen or fresh noodles, cook for 2 mins or until al dente; dried will take longer, about 5-6 mins. Drain and leave in the colander.\r\nHeat 1 tbsp of the oil, add the onion and cabbage and sauté for 5 mins until softened. Add the mushrooms and some spring onions, and sauté for 1 more min. Pour in the remaining sesame oil and the noodles. If using cold noodles, let them heat through before adding the ingredients for the sauce – otherwise tip in straight away and keep stir-frying until sticky and piping hot. Sprinkle with the remaining spring onions.',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg',
        strTags:	'LowCalorie',
        strYoutube:	'https://www.youtube.com/watch?v=5Iy0MCowSvA',
        strIngredient1:	'Udon Noodles',
        strIngredient2:	'Sesame Seed Oil',
        strIngredient3:	'Onion',
        strIngredient4:	'Cabbage',
        strIngredient5:	'Shiitake Mushrooms',
        strIngredient6:	'Spring Onions',
        strIngredient7:	'Mirin',
        strIngredient8:	'Soy Sauce',
        strIngredient9:	'Caster Sugar',
        strIngredient10:	'Worcestershire Sauce',
        strIngredient11:	'',
        strIngredient12:	'',
        strIngredient13:	'',
        strIngredient14:	'',
        strIngredient15:	'',
        strIngredient16:	'',
        strIngredient17:	'',
        strIngredient18:	'',
        strIngredient19:	'',
        strIngredient20:	'',
        strMeasure1:	'250g',
        strMeasure2:	'2 tbs',
        strMeasure3:	'1 sliced',
        strMeasure4:	'0.25',
        strMeasure5:	'10',
        strMeasure6:	'4',
        strMeasure7:	'4 tbsp',
        strMeasure8:	'2 tbs',
        strMeasure9:	'1 tblsp ',
        strMeasure10:	'1 tblsp ',
        strMeasure11:	'',
        strMeasure12:	'',
        strMeasure13:	'',
        strMeasure14:	'',
        strMeasure15:	'',
        strMeasure16:	'',
        strMeasure17:	'',
        strMeasure18:	'',
        strMeasure19:	'',
        strMeasure20:	'',
        strSource:	'https://www.bbcgoodfood.com/recipes/yaki-udon',
        strImageSource:	null,
        strCreativeCommonsConfirmed:	null,
        dateModified:	null,
      },
    ],
  );
  expect(fetch.mock.calls.length).toEqual(1);
});

test('getMealByCateg returns the correct array of objects from the fetch', async () => {
  fetch.mockResponseOnce(JSON.stringify({
    meals: [
      {
        strMeal:	'Roast fennel and aubergine paella',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/1520081754.jpg',
        idMeal:	'52942',
      },
      {
        strMeal:	'Vegan Chocolate Cake',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg',
        idMeal:	'52794',
      },
      {
        strMeal:	'Vegan Lasagna',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg',
        idMeal:	'52775',
      },
    ],
  }));
  const res = await getMealByCateg('Vegan');
  expect(res).toEqual(
    [
      {
        strMeal:	'Roast fennel and aubergine paella',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/1520081754.jpg',
        idMeal:	'52942',
      },
      {
        strMeal:	'Vegan Chocolate Cake',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg',
        idMeal:	'52794',
      },
      {
        strMeal:	'Vegan Lasagna',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg',
        idMeal:	'52775',
      },
    ],
  );
  expect(fetch.mock.calls.length).toEqual(1);
});

test('getMealDetails returns the correct meal object passing the meal Id', async () => {
  fetch.mockResponseOnce(JSON.stringify({
    meals: [
      {
        idMeal:	'52768',
        strMeal: 'Apple Frangipan Tart',
        strDrinkAlternate:	null,
        strCategory:	'Dessert',
        strArea:	'British',
        strInstructions:	'Preheat the oven to 200C…e fraiche or ice cream.',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
        strTags:	'Tart,Baking,Fruity',
        strYoutube:	'https://www.youtube.com/watch?v=rp8Slv4INLk',
        strIngredient1:	'butter',
        strIngredient2:	'Bramley apples',
        strIngredient3:	'butter, softened',
        strIngredient4:	'caster sugar',
        strIngredient5:	'free-range eggs, beaten',
        strIngredient6:	'ground almonds',
        strIngredient7:	'almond extract',
        strIngredient8:	'flaked almonds',
        strIngredient9:	'',
        strIngredient10:	'',
        strIngredient11:	'',
        strIngredient12:	'',
        strIngredient13:	'',
        strIngredient14:	'',
        strIngredient15:	'',
        strIngredient16:	null,
        strIngredient17:	null,
        strIngredient18:	null,
        strIngredient19:	null,
        strIngredient20:	null,
        strMeasure1:	'175g/6oz',
        strMeasure2:	'75g/3oz',
        strMeasure3:	'200g/7oz',
        strMeasure4:	'75g/3oz',
        strMeasure5:	'75g/3oz',
        strMeasure6:	'2',
        strMeasure7:	'75g/3oz',
        strMeasure8:	'1 tsp',
        strMeasure9:	'50g/1¾oz',
        strMeasure10:	'',
        strMeasure11:	'',
        strMeasure12:	'',
        strMeasure13:	'',
        strMeasure14:	'',
        strMeasure15:	'',
        strMeasure16:	null,
        strMeasure17:	null,
        strMeasure18:	null,
        strMeasure19:	null,
        strMeasure20:	null,
        strSource:	null,
        strImageSource:	null,
        strCreativeCommonsConfirmed:	null,
        dateModified:	null,
      },
    ],
  }));
  const res = await getMealDetails('52768');
  expect(res).toEqual(
    [
      {
        idMeal:	'52768',
        strMeal: 'Apple Frangipan Tart',
        strDrinkAlternate:	null,
        strCategory:	'Dessert',
        strArea:	'British',
        strInstructions:	'Preheat the oven to 200C…e fraiche or ice cream.',
        strMealThumb:	'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
        strTags:	'Tart,Baking,Fruity',
        strYoutube:	'https://www.youtube.com/watch?v=rp8Slv4INLk',
        strIngredient1:	'butter',
        strIngredient2:	'Bramley apples',
        strIngredient3:	'butter, softened',
        strIngredient4:	'caster sugar',
        strIngredient5:	'free-range eggs, beaten',
        strIngredient6:	'ground almonds',
        strIngredient7:	'almond extract',
        strIngredient8:	'flaked almonds',
        strIngredient9:	'',
        strIngredient10:	'',
        strIngredient11:	'',
        strIngredient12:	'',
        strIngredient13:	'',
        strIngredient14:	'',
        strIngredient15:	'',
        strIngredient16:	null,
        strIngredient17:	null,
        strIngredient18:	null,
        strIngredient19:	null,
        strIngredient20:	null,
        strMeasure1:	'175g/6oz',
        strMeasure2:	'75g/3oz',
        strMeasure3:	'200g/7oz',
        strMeasure4:	'75g/3oz',
        strMeasure5:	'75g/3oz',
        strMeasure6:	'2',
        strMeasure7:	'75g/3oz',
        strMeasure8:	'1 tsp',
        strMeasure9:	'50g/1¾oz',
        strMeasure10:	'',
        strMeasure11:	'',
        strMeasure12:	'',
        strMeasure13:	'',
        strMeasure14:	'',
        strMeasure15:	'',
        strMeasure16:	null,
        strMeasure17:	null,
        strMeasure18:	null,
        strMeasure19:	null,
        strMeasure20:	null,
        strSource:	null,
        strImageSource:	null,
        strCreativeCommonsConfirmed:	null,
        dateModified:	null,
      },
    ],
  );
  expect(fetch.mock.calls.length).toEqual(1);
});
